//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayData.Models.TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
