//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JayData.Models.TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Todo { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Developer Developer { get; set; }
    }
}
